version: "3.7"
services:
  nginx:
    image: ${IMAGE_NGINX}
    ports:
      - 80:80
    volumes:
      - ${ROOT_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  mysql80:
    image: ${IMAGE_MYSQL_80}
    volumes:
      - ${DATA_DIR}/mysql80:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    command:
      - --innodb-use-native-aio=OFF # must be off on windows
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    restart: always
  adminer:
    image: ${IMAGE_ADMINER}
    restart: always
